# Generated by Django 4.2.13 on 2024-06-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.CharField(max_length=100),
        ),
    ]
